### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by qwe252500804** [CRAZYShimakaze/zhenxun_extensive_plugin#108]
## 概述
在库里下载的zhenxun安装插件后报错
## 系统环境
windows server 2025

## 重现步骤
安装插件后启动报错

## Bug行为
真寻如何反馈

## 附件
附上图片或日志，日志请用格式：
 
> ```
> 日志内容
11-09 23:21:48 [ERROR] nonebot | Failed to import "24_point"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot\bot.py", line 24, in <module>
    nonebot.load_plugins("zhenxun/plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\zhenxun_bot\zhenxun\plugins\24_point\__init__.py", line 5, in <module>
    from models.bag_user import BagUser
ModuleNotFoundError: No module named 'models'

**Comment by l3nt7ibr** [comment]
你需要提前下载这个前置插件才能让其他插件正常使用
[plugin_utils](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/tree/main/plugin_utils)

**Comment by qwe252500804** [comment]
> 你需要提前下载这个前置插件才能让其他插件正常使用 [plugin_utils](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/tree/main/plugin_utils)

是直接放插件 文件夹里吗

**Comment by l3nt7ibr** [comment]
> > 你需要提前下载这个前置插件才能让其他插件正常使用 [plugin_utils](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/tree/main/plugin_utils)
> 
> 是直接放插件 文件夹里吗

跟你下载的其他插件放同一个文件夹下

**Comment by qwe252500804** [comment]
11-09 23:49:18 [ERROR] nonebot | Failed to import "genshin_recommend"
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot\bot.py", line 24, in <module>
    nonebot.load_plugins("zhenxun/plugins")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\load.py", line 51, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 203, in load_all_plugins
    return set(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 169, in load_plugin
    module = importlib.import_module(self._searched_plugin_ids[name])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-u0GqDEDQ-py3.11\Lib\site-packages\nonebot\plugin\manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\zhenxun_bot\zhenxun\plugins\genshin_recommend\__init__.py", line 11, in <module>
    from configs.config import Config
ModuleNotFoundError: No module named 'configs'

**Comment by qwe252500804** [comment]
还是不行

**Comment by qwe252500804** [comment]
> > > 你需要提前下载这个前置插件才能让其他插件正常使用 [plugin_utils](https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/tree/main/plugin_utils)
> > 
> > 
> > 是直接放插件 文件夹里吗
> 
> 跟你下载的其他插件放同一个文件夹下

还是不行
