### ISSUE TITLE
原神角色卡片加载失败

### ISSUE THREAD

**Issue by LierJeo** [CRAZYShimakaze/zhenxun_extensive_plugin#17]
我在Windows中使用docker运行真寻bot，就是作者自己发布的docker，同时使用WSL运行docker run命令进行部署。
在把genshin_role_card文件夹放在my_plugins文件夹下，启动容器时报错。

08-16 18:09:10 [ERROR] nonebot | Failed to import "genshin_role_card"
Traceback (most recent call last):
  File "/home/zhenxun_bot/./bot.py", line 15, in <module>
    nonebot.load_plugins("my_plugins")
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zhenxun_bot/my_plugins/genshin_role_card/__init__.py", line 116, in <module>
    async def gen(event: MessageEvent, msg: list):
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 346, in _decorator
    cls.append_handler(func, parameterless=parameterless)
  File "/usr/local/lib/python3.9/site-packages/nonebot/internal/matcher.py", line 327, in append_handler
    handler_ = Dependent[Any].parse(
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 146, in parse
    field_info = dependent.parse_param(param_name, param)
  File "/usr/local/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 102, in parse_param
    raise ValueError(
ValueError: Unknown parameter msg for function <function gen at 0x7ff38d6e2820> with type <class 'list'>

这是什么错误，有什么方法解决吗

**Comment by CRAZYShimakaze** [comment]
更新到最新版本的插件，这个bug修复了。
