### ISSUE TITLE
原神角色卡与原神面板问题

### ISSUE THREAD

**Issue by Rod-fish** [CRAZYShimakaze/zhenxun_extensive_plugin#28]
原神角色卡现在我无法查看角色卡了，日志如下
```
08-24 20:46:00 [INFO] extensive_plugin | 网页打开完成！38.02561640739441s
08-24 20:46:00 [INFO] extensive_plugin | 角色列表打开完成！0.09487271308898926s
08-24 20:46:00 [INFO] extensive_plugin | 角色获取完成！['background-image: url(/ui/UI_AvatarIcon_Side_Kokomi.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Yelan.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Yae.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Yoimiya.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Kazuha.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Zhongli.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Hutao.png)', 'background-image: url(/ui/UI_AvatarIcon_Side_Ayaka.png)']
08-24 20:46:00 [INFO] extensive_plugin | 切换中文完成！
Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "div.avatar.svelte-60ptma >> nth=0"
============================================================
08-24 20:46:30 [INFO] extensive_plugin | 角色卡获取完成！
08-24 20:46:30 [INFO] nonebot | Matcher <Matcher from extensive_plugin.genshin_role_card, type=message, priority=4, temp=False> running complete
```
此时真寻返回消息角色信息失败，确认真寻版本与插件版本全部都是最新版本

替换成原神面板插件之后会出现报错无法启动，也是确认当前版本就是最新版，本地分支与github上一次更新的代码修改内容都一致
```
08-24 20:50:49 [INFO] uvicorn | Started server process [457577]
08-24 20:50:49 [INFO] uvicorn | Waiting for application startup.
08-24 20:50:49 [INFO] services | Database loaded successfully!
08-24 20:50:49 [INFO] nonebot_plugin_apscheduler | Scheduler Started
08-24 20:50:49 [WARNING] basic_plugins | 配置文件 模块：genshin_role_card 获取 plugin_name 失败...'NoneType' object has no attribute 'module'
08-24 20:50:50 [INFO] basic_plugins | 已成功加载 75 个非限制插件.
08-24 20:50:50 [INFO] utils | 已成功加载 7 个Cd限制.
08-24 20:50:50 [INFO] utils | 已成功加载 13 个Block限制.
08-24 20:50:50 [INFO] utils | 已成功加载 1 个Count限制.
08-24 20:50:50 [INFO] basic_plugins | genshin_role_card:原神角色卡 插件疑似已删除，加载5次失败后将清除对应插件数据，当前次数：1
08-24 20:50:50 [INFO] basic_plugins | 初始化数据完成...
08-24 20:50:50 [WARNING] plugins | genshin_up_char 解析出错
08-24 20:50:50 [WARNING] plugins | pretty_up_char 解析出错
08-24 20:50:51 [INFO] plugins | 更新原神资源类型成功...
08-24 20:50:51 [INFO] plugins | genshin_resin_remind add_job：USER：3446278337 UID：101985439启动原神树脂提醒 
08-24 20:50:51 [INFO] plugins | genshin_sign add_job：USER：3446278337 UID：101985439 2022-08-25 09:06:38.366144+08:00 原神自动签到
08-24 20:50:56 [ERROR] uvicorn | Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f126c348a90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CRAZYShimakaze/zhenxun_extensive_plugin/main/genshin_role_info/__init__.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f126c348a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/__init__.py", line 355, in check_update
    version = requests.get(url)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CRAZYShimakaze/zhenxun_extensive_plugin/main/genshin_role_info/__init__.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f126c348a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/__init__.py", line 360, in check_update
    for admin in bot.config.superusers:
AttributeError: 'NoneType' object has no attribute 'config'

08-24 20:50:56 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by Rod-fish** [comment]
我这台机器经常访问不到GitHub，不知道是不是这个问题，确实不会处理，麻烦大佬帮忙看看有没有什么别的处理方式可以解决的。。

**Comment by CRAZYShimakaze** [comment]
角色卡这个是网络问题
