### ISSUE TITLE
原神面板插件无法识别图片文件报错

### ISSUE THREAD

**Issue by Rod-fish** [CRAZYShimakaze/zhenxun_extensive_plugin#29]
日志如下，查询角色面板就出错，我这垃圾的代码技术找不到是哪个图片出了问题。。。求大佬看看
```
08-25 12:59:31 [SUCCESS] nonebot | ONEBOT V11 2058793645 | [message.private.friend]: Message -289128224 from 2809778709 "钟离面板"
08-25 12:59:31 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
08-25 12:59:31 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
08-25 12:59:31 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
08-25 12:59:31 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
08-25 12:59:31 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
08-25 12:59:31 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
08-25 12:59:31 [INFO] nonebot | Event will be handled by <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False>
08-25 12:59:33 [INFO] nonebot | Matcher <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False> running complete
08-25 12:59:33 [ERROR] nonebot | Running matcher <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False> failed.
Traceback (most recent call last):
  File "/root/bot/zhenxun_bot-main/bot.py", line 21, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/__init__.py", line 79, in _
    await gen(event, str(uid), role)
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/__init__.py", line 275, in gen
    img = await draw_role_card(uid, role_data)
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/data_source/draw_role_card.py", line 166, in draw_role_card
    skill_icon = await get_img(
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/utils/aiorequests.py", line 99, in get_img
    img = Image.open(BytesIO(resp))
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 3008, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f5f148f8a90>
```

**Comment by NoctisRen** [comment]
data_source/draw_role_card.py
解注14-17行，替换18-21行试试。

**Comment by NoctisRen** [comment]
解注14-17行替换18-21行试试。

**Comment by Rod-fish** [comment]
感谢大佬，现在可以用了！

**Comment by Rod-fish** [comment]
感谢大佬解惑，现在可以用了

**Comment by CRAZYShimakaze** [comment]
> 感谢大佬解惑，现在可以用了

这个还是你的网络问题，之前被注释掉的接口没有3.0新角色的信息，新角色是查不了的。
你还是想办法把网络连接性弄弄好吧。
用这个网站进行测试[Enka](https://enka.network)
