### ISSUE TITLE
两次更新面板的时候偶然发现的错误，不知道是什么情况，但是确实更新失败查不到角色

### ISSUE THREAD

**Issue by Rod-fish** [CRAZYShimakaze/zhenxun_extensive_plugin#31]
这是第一次更新发生的错误，我自己试了试确实是正常可以用的，很奇怪这里为什么他不能用
```
08-25 18:04:35 [SUCCESS] nonebot | ONEBOT V11 2058793645 | [message.group.normal]: Message -194350079 from 2524392255@[群:8675424536] "更新面板 102737723"
08-25 18:04:35 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
08-25 18:04:35 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
08-25 18:04:35 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
08-25 18:04:35 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
08-25 18:04:35 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
08-25 18:04:35 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
08-25 18:04:35 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
08-25 18:04:35 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
08-25 18:04:35 [INFO] nonebot | Event will be handled by <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False>
08-25 18:04:35 [INFO] nonebot | Matcher <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False> running complete
08-25 18:04:35 [ERROR] nonebot | Running matcher <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False> failed.
Traceback (most recent call last):
  File "/root/bot/zhenxun_bot-main/bot.py", line 21, in <module>
    nonebot.run()
  File "/usr/local/lib/python3.10/dist-packages/nonebot/__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/drivers/fastapi.py", line 170, in run
    uvicorn.run(
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/root/bot/zhenxun_bot-main/extensive_plugin/genshin_role_info/__init__.py", line 71, in _
    uid = await Genshin.get_user_uid(get_message_at(event.json())[0])
IndexError: list index out of range
```
这是第二次发生的错误
```
08-25 18:06:52 [SUCCESS] nonebot | ONEBOT V11 2058793645 | [message.group.normal]: Message -456717973 from 2524392255@[群:756432354] "更新面板"
08-25 18:06:52 [INFO] nonebot | Event will be handled by <Matcher from plugins.mute, type=message, priority=1, temp=False>
08-25 18:06:52 [INFO] nonebot | Event will be handled by <Matcher from plugins.black_word, type=message, priority=1, temp=False>
08-25 18:06:52 [INFO] nonebot | Event will be handled by <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False>
08-25 18:06:52 [INFO] nonebot | Event will be handled by <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False>
08-25 18:06:52 [INFO] nonebot | Matcher <Matcher from plugins.black_word, type=message, priority=1, temp=False> running complete
08-25 18:06:52 [INFO] nonebot | Matcher <Matcher from plugins.mute, type=message, priority=1, temp=False> running complete
08-25 18:06:52 [INFO] nonebot | Matcher <Matcher from plugins.parse_bilibili_json, type=message, priority=1, temp=False> running complete
08-25 18:06:52 [INFO] nonebot | Matcher <Matcher from basic_plugins.chat_history.chat_message, type=message, priority=1, temp=False> running complete
08-25 18:06:52 [INFO] nonebot | Event will be handled by <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False>
第329行发生error为: 'playerInfo'
08-25 18:06:59 [INFO] nonebot | Matcher <Matcher from extensive_plugin.genshin_role_info, type=message, priority=4, temp=False> running complete
```

**Comment by CRAZYShimakaze** [comment]
第一个，命令错误
第二个，请提供uid
