### ISSUE TITLE
催更原神角色面板

### ISSUE THREAD

**Issue by wlz-remake** [CRAZYShimakaze/zhenxun_extensive_plugin#42]
## 概述
版本更新后，如果展示柜里带有草神，“更新面板”指令就会挂掉

## 系统环境
![image](https://user-images.githubusercontent.com/105090141/199399613-e7abc051-1917-4c83-9886-e91add0eb4df.png)

## 重现步骤
展示柜里带有草神，发送“更新面板”指令

## Bug行为
真寻对展示柜里带有草神的用户指令无响应

## 附件

```
11-02 12:31:09 [SUCCESS] nonebot | OneBot V11 2106650688 | [message.group.normal]: Message 2096766045 from 1012554228@[
群:1009848583] "更新面板"
11-02 12:31:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
11-02 12:31:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
11-02 12:31:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
11-02 12:31:09 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
11-02 12:31:09 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
11-02 12:31:09 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
11-02 12:31:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=my_plugin.genshin_role_info)
11-02 12:31:11 [INFO] nonebot | Matcher(type='message', module=my_plugin.genshin_role_info) running complete
11-02 12:31:11 [ERROR] nonebot | Running Matcher(type='message', module=my_plugin.genshin_role_info) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\uvi
corn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\uvi
corn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\__init__.py", line 87, in _
    await update(uid)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\__init__.py", line 286, in update
    player_info.set_role(role)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\utils\card_utils.py", line 71, in se
t_role
    role_info['元素'] = role_data[role_name]["element"]
KeyError: None
```

**Comment by CRAZYShimakaze** [comment]
已更新
