### ISSUE TITLE
[原神角色面板]部分角色无法查询

### ISSUE THREAD

**Issue by wlz-remake** [CRAZYShimakaze/zhenxun_extensive_plugin#43]
## 概述
查询角色面板时QQ机器人无响应，后台报错
目前已知的有鹿野院平藏和七七，报错相同

## 系统环境
windows server 2019

## 重现步骤
查询鹿野院平藏或七七的面板，uid：173272299

## Bug行为
真寻无响应，后台报错

## 附件

```
11-03 00:02:46 [SUCCESS] nonebot | OneBot V11 2106650688 | [message.group.normal]: Message 201879981 from 3012352785@[群

:928213128] "珊瑚宫心海面板"
11-03 00:02:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
11-03 00:02:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
11-03 00:02:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
11-03 00:02:46 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
11-03 00:02:46 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
11-03 00:02:46 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
11-03 00:02:46 [INFO] nonebot | Event will be handled by Matcher(type='message', module=my_plugin.genshin_role_info)
11-03 00:02:46 [INFO] nonebot | Matcher(type='message', module=my_plugin.genshin_role_info) running complete
11-03 00:02:46 [ERROR] nonebot | Running Matcher(type='message', module=my_plugin.genshin_role_info) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\uvi
corn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\uvi
corn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Program Files\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-KE5KzDFr-py3.9\lib\site-packages\non
ebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\__init__.py", line 89, in _
    await gen(event, uid, role)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\__init__.py", line 244, in gen
    img, score = await draw_role_card(uid, role_data)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\data_source\draw_role_card.py", line
 99, in draw_role_card
    dmg_img = draw_dmg_pic(dmg_img)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\my_plugin\genshin_role_info\data_source\draw_role_card.py", line
 35, in draw_dmg_pic
    if len(dmg.get('额外说明', [])[0]) >= 26:
IndexError: list index out of range
```

**Comment by McElaga** [comment]
今天也遇到了，而且正好是七七

**Comment by CRAZYShimakaze** [comment]
已修复
