### ISSUE TITLE
24点启动没有问题，输入”24点“后报错，输入”结束24点“正常。

### ISSUE THREAD

**Issue by 4Nanai** [CRAZYShimakaze/zhenxun_extensive_plugin#46]
## 概述
启动没有问题，输入”24点“后报错，输入”结束24点“正常。
## 系统环境
windows

## 重现步骤
> 11-04 00:02:21 [ERROR] utils | 下载 https://raw.githubusercontent.com/noneplugin/nonebot-plugin-handle/main/nonebot_plugin_handle/resources/fonts/Consolas.ttf 未知错误 <class 'httpx.ReadError'>：.. Path：C:\Users\Administrator\Desktop\zhenxun_bot-main\resources\font\Consolas.ttf
11-04 00:02:21 [INFO] nonebot | Matcher(type='message', module=extensive_plugin.24_point) running complete
11-04 00:02:21 [ERROR] nonebot | Running Matcher(type='message', module=extensive_plugin.24_point) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\extensive_plugin\24_point\__init__.py", line 55, in _
    await handle.get_tff()
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\extensive_plugin\24_point\data_source.py", line 25, in get_tff
    self.font_char = await load_font("Consolas.ttf", font_size_char)
  File "C:\Users\Administrator\Desktop\zhenxun_bot-main\extensive_plugin\24_point\utils.py", line 24, in load_font
    return ImageFont.truetype(str(tff_path), fontsize, encoding="utf-8")
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\PIL\ImageFont.py", line 959, in truetype
    return freetype(font)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\PIL\ImageFont.py", line 956, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-cjzdVN1J-py3.9\lib\site-packages\PIL\ImageFont.py", line 247, in __init__
    self.font = core.getfont(
OSError: cannot open resource

## Bug行为
真寻不回复

**Comment by 4Nanai** [comment]
> 
疑似是
https://raw.githubusercontent.com/noneplugin/nonebot-plugin-handle/main/nonebot_plugin_handle/resources/fonts/
这个连接嘎了，不知道这个指向的是哪个字体文件，或者说我应该在utils.py里指向我本地的字体文件？

**Comment by CRAZYShimakaze** [comment]
[https://raw.githubusercontent.com/noneplugin/nonebot-plugin-handle/main/nonebot_plugin_handle/resources/fonts/Consolas.ttf](url)
这个链接直接点击是可以下载字体文件的，你可以手动下载然后放到resources\font\目录里再试试。
