### ISSUE TITLE
原神角色面板插件使用更新面板没有回应

### ISSUE THREAD

**Issue by CaffuChin0** [CRAZYShimakaze/zhenxun_extensive_plugin#57]
02-08 08:18:45 [SUCCESS] nonebot | OneBot V11 384112569 | [message.group.normal]: Message 478370600 from 583625721@[群:107876145] "更新面板"
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.genshin_role_info)
02-08 08:18:45 [SUCCESS] nonebot | OneBot V11 384112569 | [message.group.normal]: Message 1803840446 from 2074591573@[群:107876145] "[CQ:image,file=0cff7cd58621093618afc624d2b1f953.image,subType=1,url=https://gchat.qpic.cn/gchatpic_new/2074591573/2050876145-2550526530-0CFF7CD58621093618AFC624D2B1F953/0?term=3&amp;is_origin=0]"
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.mute)
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.black_word)
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.parse_bilibili_json)
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.black_word) running complete
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.parse_bilibili_json) running complete
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.mute) running complete
02-08 08:18:45 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.fudu)
02-08 08:18:45 [INFO] utils | 下载 https://gchat.qpic.cn/gchatpic_new/2074591573/2050876145-2550526530-0CFF7CD58621093618AFC624D2B1F953/0?term=3&is_origin=0 成功.. Path：C:\Users\Administrator\Desktop\zhenxun_bot\resources\temp\compare_107876145_img.jpg
02-08 08:18:45 [INFO] nonebot | Matcher(type='message', module=plugins.fudu) running complete
02-08 08:18:48 [INFO] nonebot | Matcher(type='message', module=plugins.genshin_role_info) running complete
02-08 08:18:48 [ERROR] nonebot | Running Matcher(type='message', module=plugins.genshin_role_info) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\zhenxun_bot\bot.py", line 21, in <module>
    nonebot.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\Desktop\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-7NSuiggF-py3.9\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Desktop\zhenxun_bot\plugins\genshin_role_info\__init__.py", line 147, in _
    await update(event, uid, group_save=True)
  File "C:\Users\Administrator\Desktop\zhenxun_bot\plugins\genshin_role_info\__init__.py", line 373, in update
    player_info.set_player(data['playerInfo'])
KeyError: 'playerInfo'

**Comment by CRAZYShimakaze** [comment]
请更新到插件最新版本
