### ISSUE TITLE
24点报错

### ISSUE THREAD

**Issue by dong2005923** [CRAZYShimakaze/zhenxun_extensive_plugin#62]
02-24 21:17:52 [INFO] nonebot | Event will be handled by Matcher(type='message', module=plugins.24_point)
02-24 21:17:52 [INFO] nonebot | Matcher(type='message', module=plugins.24_point) running complete
02-24 21:17:52 [ERROR] nonebot | Running Matcher(type='message', module=plugins.24_point) failed.
Traceback (most recent call last):
  File "D:\msys2\home\dong\TRSS_Zhenxun\Zhenxun\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\msys2\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-9TOne0dY-py3.10\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "D:\msys2\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-9TOne0dY-py3.10\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "D:\msys2\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-9TOne0dY-py3.10\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "D:\msys2\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-9TOne0dY-py3.10\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\msys2\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-9TOne0dY-py3.10\lib\site-packages\PIL\ImageFont.py", line 973, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\msys2\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-9TOne0dY-py3.10\lib\site-packages\PIL\ImageFont.py", line 249, in __init__
    self.font = core.getfont(
OSError: unknown file format
![H2{0141_P7IGI~7Z_C_ ROH](https://user-images.githubusercontent.com/109427426/221188728-2a8531b1-8cf5-4e82-892c-36c9b578e42c.png)

**Comment by CRAZYShimakaze** [comment]
已修复
