### ISSUE TITLE
打工无法载入

### ISSUE THREAD

**Issue by dong2005923** [CRAZYShimakaze/zhenxun_extensive_plugin#63]
02-25 22:48:05 [ERROR] nonebot | Failed to import "work"
Traceback (most recent call last):
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\plugins\work\__init__.py", line 17, in <module>
    from .model import Worker
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\plugins\work\model.py", line 2, in <module>
    from services.db_context import db
ImportError: cannot import name 'db' from 'services.db_context' (D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\services\db_context.py)
![T9Y8BNQBELJK@UM)9EM9N@P](https://user-images.githubusercontent.com/109427426/221364206-bdd672fe-0e19-4a41-b153-810632030fd1.png)

**Comment by niucattle** [comment]
我也这样欸

**Comment by niucattle** [comment]
换了个服务器 转移了一下数据后 再安装这个插件 就报错了

**Comment by MobiusT** [comment]
https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/pull/61#issue-1590629581

此pr会在真寻更新发行版后正式并入

**Comment by Nenot233** [comment]
03-01 08:52:11 [ERROR] nonebot | Failed to import "work"
Traceback (most recent call last):

  File "D:\BOT\zhenxun_bot\bot.py", line 16, in <module>
    nonebot.load_plugins("extensive_plugin")
    │       └ <function load_plugins at 0x0000019D07759550>
    └ <module 'nonebot' from 'C:\\Users\\Administrator\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\zhenxun-bot-l9AehN_x-py3.9\\l...

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
           │       └ <function PluginManager.load_all_plugins at 0x0000019D0774DDC0>
           └ PluginManager(plugins=set(), search_path={'extensive_plugin'})

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
                  │    │           │         │       │    └ <property object at 0x0000019D0774BA40>
                  │    │           │         │       └ PluginManager(plugins=set(), search_path={'extensive_plugin'})
                  │    │           │         └ 'work'
                  │    │           └ 'work'
                  │    └ <function PluginManager.load_plugin at 0x0000019D0774DD30>
                  └ PluginManager(plugins=set(), search_path={'extensive_plugin'})

> File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
             │         └ <function import_module at 0x0000019D04D655E0>
             └ <module 'importlib' from 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'extensive_plugin.work'
           │          └ <function _gcd_import at 0x0000019D046D13A0>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-l9AehN_x-py3.9\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
                        └ <module 'extensive_plugin.work' from 'D:\\BOT\\zhenxun_bot\\extensive_plugin\\work\\__init__.py'>

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "D:\BOT\zhenxun_bot\extensive_plugin\work\__init__.py", line 85, in <module>
    if len(moneys) < timu_num:
           │         └ '6'
           └ '[0, 50, 100, 150, 200, 250]'

TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by MobiusT** [comment]
[commit](https://github.com/HibiKier/zhenxun_bot/commit/401029bd2766c3727443ab2b4b013eec32fef45a)请更新真寻

**Comment by Nenot233** [comment]
更新后还是会出现这个报错

**Comment by MobiusT** [comment]
将configs/config.yaml及data/configs/plugins2config.yaml两个文件work的配置全部删除后重启即可

**Comment by dong2005923** [comment]
> 将configs/config.yaml及data/configs/plugins2config.yaml两个文件work的配置全部删除后重启即可

似乎又出现了新的报错03-01 21:20:07 [ERROR] nonebot | Failed to import "work"
Traceback (most recent call last):
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\bot.py", line 14, in <module>
    nonebot.load_plugins("plugins")
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\home\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-ETT07Wgi-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\plugins\work\__init__.py", line 17, in <module>
    from .model import Worker
  File "D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\plugins\work\model.py", line 2, in <module>
    from services.db_context import db
ImportError: cannot import name 'db' from 'services.db_context' (D:\zhenxun\home\dong\TRSS_Zhenxun\Zhenxun\services\db_context.py)

**Comment by MobiusT** [comment]
日志似乎不全，看上去和插件本身关系也不大，你在第一次ImportError: cannot import name 'db' from 'services.db_context'后进行了哪些操作

**Comment by MobiusT** [comment]
> https://github.com/CRAZYShimakaze/zhenxun_extensive_plugin/pull/61#issue-1590629581
> 
> 此pr会在真寻更新发行版后正式并入

看懂你日志了，你这个和最开始是同一个报错，解决办法也是一样的啊，手动修改下这个pr中的改动就行
